sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test

after_success:
  - docker build -t burdianov/multi-client ./client
  - docker build -t burdianov/multi-nginx ./enginx
  - docker build -t burdianov/multi-server ./server
  - docker build -t burdianov/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the images to DockerHub
  - docker push burdianov/multi-client
  - docker push burdianov/multi-nginx
  - docker push burdianov/multi-server
  - docker push burdianov/multi-worker
